feature/add_admin_article_index
nishinotakay/teac-output-new pull request #117
Opened 2023-05-12 13:44 UTC by nagaminejun

**PR概要**
管理者画面で、記事投稿機能、管理者の記事一覧画面機能、管理者含めuserの全投稿記事一覧を実装

仕様書のNo.1、No.2、No.4
https://docs.google.com/spreadsheets/d/11AWBG5VwWw5xrv0Fc_TAYBxQ4wbvGchMehzSHj-z3jw/edit#gid=340728998

管理者ログイントップページ
http://localhost:3000/admins/sign_in

email: 'test_admin@gmail.com',
name: 'テストadmin1',
password: 'password'

**実装内容**
管理者の記事投稿、記事一覧機能、全投稿記事一覧機能を実装。

adminログイン時の画面　変更点
・サイドバーの「投稿記事一覧」ボタンをuserと同じように「記事一覧」に変更。
・ヘッダーに「投稿した記事一覧」と「記事投稿」ボタンを表示

**今後の課題**
・ログイン後のトップ画面→記事一覧ボタン押下後に、右上ユーザーアイコン押下するもドロップダウン表示されず。が、リロードや記事一覧ボタン再度押下するとドロップダウン表示される。原因究明目指します。
・引き続き仕様書に沿って実装します。

**実装画面スクリーンショットのスプレッドシートのリンク**

https://docs.google.com/spreadsheets/d/1jk1GomJMRloK4zCPtFinvBWzT8vk6fCijXaklKbKdZU/edit#gid=0

**備考**
実装内容が多く、編集したファイル多くすみません。プルリクをこまめにしておくべきだったかと考えております。

**お伝えしたいこと**
管理者記事投稿機能の追加実装を取り組んでいますが、追加に伴い、user側の記事一覧画面も変更加えています。
理由：userに紐づくarticlesデータに加え、adminに紐づくarticles データが混在したため、下記ファイル修正。
app/views/users/articles/shared/_articles_table.html.erb

2023-05-13 10:32 UTC, badminto commented
お疲れ様です！すみません、管理者のpassって、
  email: 'test_admin@gmail.com',
  name: 'テストadmin1',
  password: 'password'
でよかったでしょうか？「記事一覧」・「記事投稿」ボタンが見当たらなくて・・・
<img width="942" alt="image" src="https://github.com/nishinotakay/teac-output-new/assets/97861380/5652594f-0338-4fbb-a8c0-26174f03fd29">
また変なこと言ってたらすみません。。。m(_ _)m

2023-05-13 12:16 UTC, nagaminejun commented
@badminto 
佐藤さんコメントありがとうございます。

今回のプルリクエストのブランチ、Feature/add admin article index #117　を佐藤さんのローカル環境にfetch して、ブランチを取り込んで動作確認されていますか？もししている状態でコメントされてたら大変すみません！！
※  git push origin  した際、ブランチ名にハイフンつけたのですが何故か反映されておらず。不具合起きてたらすみません。

adminのログイン情報提供と、スクショ添付とても助かります😄
スクショ見ると、adminログイン時サイドバーに「投稿記事一覧」と見えます。マージ前のdevelopブランチでアプリを開いていると考えられます。
※私側の手違いでヘッダ、サイドバー適用されてないようでしたら申し訳ないです。

私のPRでは「投稿記事一覧」ボタンを→user画面と統一目的で「記事一覧」ボタンに変更しています。押下後の遷移先は同じです。

git fetch についての記事、念の為添付します。
https://docs.github.com/ja/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/checking-out-pull-requests-locally

2023-05-14 01:46 UTC, mockysunshinework commented
@nagaminejun 
おつかれさまです。
実装画面イメージのスクショのリンクに権限かかっているようでアクセスできません。先ほどリクエスト送ったのでかくにんお願いします🙇

2023-05-15 05:28 UTC, badminto commented
@nagaminejun 島人ぬ
お疲れ様です！git fetch して長嶺さんの実装見ることが出来ました。長嶺さんのおかげでgit fetch、git stashの使い方がわかりました。ありがとうございます！m(_ _)m
approveしました。
<img width="945" alt="image" src="https://github.com/nishinotakay/teac-output-new/assets/97861380/19e73e2c-d8b9-41d3-8e21-73172c548809">

2023-05-15 05:31 UTC, badminto approved these changes

2023-05-15 10:16 UTC, nagaminejun commented
３点リーダーから記事削除後の遷移先で、記事投稿ボタンが非表示になるバグを修正しました。

エラー原因
削除後のfullpath が、admins/dash_boards.1　と後ろにID が引数として渡されていて、

_header.html.erb
<% if request.fullpath == "/admins/articles" || request.fullpath == "/admins/dash_boards" %>
== でリンクを完全一致でtrue、ボタン表示にする書き方のため、else 判定の遷移となっていた。

変更後
<% if request.fullpath.include?("/admins/articles") || request.fullpath.include?("/admins/dash_boards") %>
include?　でリンク文を含む、の指示に変更しました。
今後管理者が増えてadmins/dash_boards.2、admins/dash_boards.3　となっても表示されるはずです。

2023-05-16 08:20 UTC, mockysunshinework requested changes
@nagaminejun 
2点コメントしてます。確認お願いします。
その他は仕様書のNo.1、No.2、No.4について仕様書の通り動作することを確認しました！

2023-05-16 08:20 UTC, mockysunshinework commented on app/views/admins/articles/index.html.erb
> +</div>
@nagaminejun 
最終行に改行をお願いします！

2023-05-16 08:20 UTC, mockysunshinework commented on app/views/admins/articles/show.html.erb
> +</div>
@nagaminejun 
最終行に改行をお願いします！

2023-05-18 11:30 UTC, nagaminejun commented
@mockysunshinework 
お疲れ様です！対応が遅れてしまい大変すみません。
ご指摘の箇所２点、最終行に改行をして再度PRいたしました。
ご確認お願いしますm(_ _)m

2023-05-19 08:43 UTC, mockysunshinework approved these changes
@nagaminejun 
確認しました！問題ないと思います！

2023-05-19 09:38 UTC, nagaminejun commented
@mockysunshinework 
ありがとうございます！🙇‍♂️

2023-05-19 10:54 UTC, nagaminejun commented
PR修正しました。approve 頂いた後にPR修正して申し訳ないです。
前回MTGでご指摘された、js.file について、admin配下のjs.file を作成しましたが、不必要かつ不具合が出ますので、修正・削除しました。
admin配下の各erb.fileには、user配下のjs.file を適用するように変更しました。

2023-05-19 11:55 UTC, nishinotakaya approved these changes

2023-05-19 11:55 UTC, nishinotakaya approved these changes

2023-05-19 11:55 UTC, nishinotakaya approved these changes

2023-05-20 00:27 UTC, merged

2023-05-20 00:31 UTC, nagaminejun commented
チェックありがとうございます🙇‍♂️